const path = require("path");
var filename = "D:\\Tutorials\\NODEJS\\index01.js";
var newpath = "D:\\\\\\Tutorials\\NODEJS\\\\\\\\\\index01.js";
var newpath1 = "Nodejs\\index.js";
console.log(path.basename(filename));
console.log(__filename);
console.log(__dirname);
console.log(path.basename(__filename));
console.log(path.extname(filename));
console.log(path.dirname(filename));
console.log(path.join("users", "category", "diagram", "flowchart"));
console.log(path.join(__dirname, "users", "category", "diagram", "flowchart"));
console.log(path.join("users", "category", "diagram", "flowchart"));
console.log(path.resolve("users", "category", "diagram", "flowchart"));
console.log(path.normalize(newpath));
console.log(path.join("users", "category", "diagram", "flowchart", ".."));
console.log(path.join("users", "category", "diagram", "flowchart", "..", ".."));
console.log(path.parse(filename).base);
console.log(path.parse(filename).dir);
console.log(path.parse(filename).ext);
console.log(path.parse(filename).name);
console.log(path.parse(filename).root);
console.log(path.isAbsolute(filename));
console.log(path.isAbsolute(newpath1));
